### ISSUE TITLE
Following vagrant up, I get this message

### ISSUE THREAD

**Issue by JonTheNiceGuy** [JonTheNiceGuy/test_scuttlebutt#1]
```
Oct 22 14:44:56 ubuntu-bionic systemd[1]: Started Scuttlebot.
-- Subject: Unit scuttlebot.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit scuttlebot.service has finished starting up.
--
-- The start-up result is RESULT.
Oct 22 14:44:56 ubuntu-bionic sudo[14346]: pam_unix(sudo:session): session closed for user root
Oct 22 14:44:56 ubuntu-bionic sbot[14349]: scuttlebot 13.0.0 /home/vagrant/.ssb logging.level:notice
Oct 22 14:44:56 ubuntu-bionic sbot[14349]: my key ID: piLzWtzmNDloz6OcSeJIIfbJw7qAg39Yo8XcHRJYmFI=.ed25519
Oct 22 14:44:57 ubuntu-bionic sbot[14349]: /usr/local/lib/node_modules/scuttlebot/plugins/plugins.js:187
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:         throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+(plugin||{}).name)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:         ^
Oct 22 14:44:57 ubuntu-bionic sbot[14349]: Error: plugin at:ssb-links expected name:links but had:links2
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at Object.module.exports.loadUserPlugins (/usr/local/lib/node_modules/scuttlebot/plugins/plugins.js:187:15)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at Object.<anonymous> (/usr/local/lib/node_modules/scuttlebot/bin.js:59:32)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at Module._compile (module.js:652:30)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at Object.Module._extensions..js (module.js:663:10)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at Module.load (module.js:565:32)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at tryModuleLoad (module.js:505:12)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at Function.Module._load (module.js:497:3)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at Function.Module.runMain (module.js:693:10)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at startup (bootstrap_node.js:188:16)
Oct 22 14:44:57 ubuntu-bionic sbot[14349]:     at bootstrap_node.js:609:3
Oct 22 14:44:57 ubuntu-bionic systemd[1]: scuttlebot.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 14:44:57 ubuntu-bionic systemd[1]: scuttlebot.service: Failed with result 'exit-code'.
Oct 22 14:44:57 ubuntu-bionic systemd[1]: scuttlebot.service: Service hold-off time over, scheduling restart.
Oct 22 14:44:57 ubuntu-bionic systemd[1]: scuttlebot.service: Scheduled restart job, restart counter is at 1.
-- Subject: Automatic restarting of a unit has been scheduled
```

**Comment by JonTheNiceGuy** [comment]
Resolved via https://github.com/noffle/git-ssb-intro/pull/7
